[package]
name = "dummy_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
futures = "0.3.0"
chat_common = { path = "../common" }
crossterm = "0.27.0"